import type { DexNestActionDefinition } from "@dexnest/shared-types";

const actionIdPattern = /^[a-z][a-z0-9_-]*(\.[a-z][a-z0-9_-]*)+$/;

export const seededActions = [
  {
    id: "command.open_home",
    title: "Open Command Home",
    moduleId: "command",
    module: "command",
    description: "Open the DexNest Command home dashboard.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.command",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "command.refresh_stats",
    title: "Refresh Command Stats",
    moduleId: "command",
    module: "command",
    description: "Refresh DexNest Command local stats.",
    category: "command.stats",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "command.refresh_stats",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "command.open_palette",
    title: "Open Command Palette",
    moduleId: "command",
    module: "command",
    description: "Open DexNest Command with the action palette focused.",
    category: "command.palette",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.command",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "command.update_settings",
    title: "Update Command Access Settings",
    moduleId: "command",
    module: "command",
    description: "Update DexNest Command global shortcut settings.",
    category: "command.settings",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "command.update_settings",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "command.open_recent_activity",
    title: "Open Recent Activity",
    moduleId: "command",
    module: "command",
    description: "Show DexNest Command recent activity.",
    category: "command.activity",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "command.open_recent_activity",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  ...[
    ["system.health.open", "Open App Health", "Open the DexNest App Health dashboard.", "system.health", "safe", false],
    ["system.health.run_checks", "Run App Health Checks", "Run on-demand local DexNest safety and architecture checks.", "system.health", "safe", false],
    ["backup.open", "Open Backup Settings", "Open DexNest local backup and restore settings.", "backup", "safe", false],
    ["backup.create", "Create Local Backup", "Create a local DexNest zip backup.", "backup", "caution", false],
    ["backup.open_folder", "Open Backup Folder", "Open the local DexNest backup folder.", "backup", "safe", false],
    ["backup.preview_restore", "Preview Backup Restore", "Preview a local DexNest backup zip before restore.", "backup", "safe", false],
    ["backup.restore_confirmed", "Restore Backup", "Restore DexNest local data from a confirmed backup zip.", "backup", "danger", true]
  ].map(([id, title, description, category, dangerLevel, requiresConfirmation]): DexNestActionDefinition => ({
    id: id as string,
    title: title as string,
    moduleId: (id === "system.health.open" || id === "system.health.run_checks" ? "system" : "backup") as "system" | "backup",
    module: (id === "system.health.open" || id === "system.health.run_checks" ? "system" : "backup") as "system" | "backup",
    description: description as string,
    category: category as string,
    dangerLevel: dangerLevel as "safe" | "caution" | "danger" | "critical",
    requiresConfirmation: requiresConfirmation as boolean,
    confirmationRule: requiresConfirmation ? "Restore replaces current DexNest local data after a safety backup is created." : null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function" as const,
    handlerRef: id === "backup.open" || id === "system.health.open" ? "desktop.view.settings" : (id as string),
    allowedTriggers: ["command", "deck", "module_ui"] as Array<"command" | "deck" | "module_ui">,
    enabled: true,
    status: "available" as const
  })),
  {
    id: "dev.open_dashboard",
    title: "Open Dev Dashboard",
    moduleId: "dev",
    module: "dev",
    description: "Open the DexNest Dev dashboard placeholder.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.dev",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "deck.test_endpoint",
    title: "Test Deck Endpoint",
    moduleId: "deck",
    module: "deck",
    description: "Run a safe test through the DexNest localhost action endpoint.",
    category: "diagnostics",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "http_endpoint",
    handlerRef: "/actions/deck.test_endpoint",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  ...[
    ["deck.routine.create", "Create Deck Routine", "Create a local DexNest routine.", "deck.routines", "caution", false],
    ["deck.routine.update", "Update Deck Routine", "Update a local DexNest routine.", "deck.routines", "caution", false],
    ["deck.routine.delete", "Delete Deck Routine", "Delete a local DexNest routine.", "deck.routines", "danger", true],
    ["deck.routine.run", "Run Deck Routine", "Run a DexNest routine sequentially.", "deck.routines", "caution", false],
    ["deck.routine.reorder", "Reorder Deck Routine", "Reorder DexNest routine steps.", "deck.routines", "caution", false]
  ].map(([id, title, description, category, dangerLevel, requiresConfirmation]) => ({
    id: id as string,
    title: title as string,
    moduleId: "deck" as const,
    module: "deck" as const,
    description: description as string,
    category: category as string,
    dangerLevel: dangerLevel as "safe" | "caution" | "danger" | "critical",
    requiresConfirmation: requiresConfirmation as boolean,
    confirmationRule: requiresConfirmation ? "Deleting a routine removes it from local settings." : null,
    reversible: false,
    undoActionId: null,
    handlerType: "routine" as const,
    handlerRef: id as string,
    allowedTriggers: ["command", "deck", "routine", "module_ui"] as Array<"command" | "deck" | "routine" | "module_ui">,
    enabled: true,
    status: "available" as const
  })),
  {
    id: "clipboard.open",
    title: "Open Clipboard",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Open the DexNest Clipboard workspace.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.clipboard",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.save_current",
    title: "Save Current Clipboard",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Manually save the current text clipboard into DexNest Clipboard history.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.save_current",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.copy_plain_text",
    title: "Paste as Plain Text",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Normalize the current clipboard text as plain text.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.copy_plain_text",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.create_snippet",
    title: "Create Clipboard Snippet",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Create or update a local DexNest Clipboard snippet.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.create_snippet",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.delete_snippet",
    title: "Delete Clipboard Snippet",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Delete a local DexNest Clipboard snippet.",
    category: "clipboard",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a snippet removes it from local settings.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.delete_snippet",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.toggle_listener",
    title: "Toggle Clipboard Listener",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Enable or disable the lightweight DexNest Clipboard listener.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.toggle_listener",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.test_read_current",
    title: "Test Read Clipboard",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Read the current Clipboard preview without saving full content.",
    category: "clipboard",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.test_read_current",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.update_settings",
    title: "Update Clipboard Settings",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Update DexNest Clipboard hotkey, separator, and timeout settings.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.update_settings",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.start_multi_copy",
    title: "Start Multi-Copy",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Start a temporary DexNest multi-copy session.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.start_multi_copy",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.save_multi_copy_group",
    title: "Save Multi-Copy Group",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Save the active DexNest multi-copy session without stopping it.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.save_multi_copy_group",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.clear_multi_copy_session",
    title: "Clear Multi-Copy Session",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Clear the active DexNest multi-copy session items.",
    category: "clipboard",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Clearing the active session removes temporary multi-copy items.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.clear_multi_copy_session",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.copy_combined_group",
    title: "Copy Combined Clipboard Group",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Copy all active or saved multi-copy items as one combined Clipboard value.",
    category: "clipboard",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.copy_combined_group",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.delete_multi_copy_group",
    title: "Delete Multi-Copy Group",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Delete a saved DexNest multi-copy group.",
    category: "clipboard",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a multi-copy group removes it from local settings.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.delete_multi_copy_group",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.stop_multi_copy",
    title: "Stop Multi-Copy",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Stop and optionally name the current DexNest multi-copy group.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.stop_multi_copy",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.copy_history_item",
    title: "Copy Clipboard History Item",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Copy a DexNest Clipboard history item back to the system clipboard.",
    category: "clipboard",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.copy_history_item",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.assign_slot",
    title: "Assign Clipboard Slot",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Assign the current clipboard text to a numbered DexNest Clipboard slot.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.assign_slot",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.copy_slot",
    title: "Copy Clipboard Slot",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Copy a saved DexNest Clipboard slot back to the system clipboard.",
    category: "clipboard",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.copy_slot",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.clear_history",
    title: "Clear Clipboard History",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Clear local DexNest Clipboard history.",
    category: "clipboard",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Clearing Clipboard history removes local saved clipboard items.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.clear_history",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "clipboard.cleanup_history",
    title: "Cleanup Clipboard History",
    moduleId: "clipboard",
    module: "clipboard",
    description: "Remove DexNest Clipboard history items older than the configured retention window.",
    category: "clipboard",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "clipboard.cleanup_history",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.open",
    title: "Open Drop",
    moduleId: "drop",
    module: "drop",
    description: "Open the DexNest Drop local handoff workspace.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.drop",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.copy_phone_url",
    title: "Copy Drop Phone URL",
    moduleId: "drop",
    module: "drop",
    description: "Copy the DexNest Drop LAN phone URL.",
    category: "drop",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "drop.copy_phone_url",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.create_text_drop",
    title: "Create Text Drop",
    moduleId: "drop",
    module: "drop",
    description: "Create a temporary local text drop.",
    category: "drop",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "drop.create_text_drop",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.send_clipboard_to_drop",
    title: "Send Current Clipboard to Drop",
    moduleId: "drop",
    module: "drop",
    description: "Create a temporary Drop item from the current text clipboard.",
    category: "drop",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "drop.send_clipboard_to_drop",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.add_outgoing_file",
    title: "Add Outgoing Drop File",
    moduleId: "drop",
    module: "drop",
    description: "Select a local file and add it to the DexNest Drop outgoing shelf.",
    category: "drop",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "drop.add_outgoing_file",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.remove_outgoing_file",
    title: "Remove Outgoing Drop File",
    moduleId: "drop",
    module: "drop",
    description: "Remove a file from the DexNest Drop outgoing shelf.",
    category: "drop",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Removing an outgoing file deletes the Drop copy.",
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "drop.remove_outgoing_file",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.clear_outgoing",
    title: "Clear Drop Outgoing Shelf",
    moduleId: "drop",
    module: "drop",
    description: "Clear outgoing DexNest Drop text and file items.",
    category: "drop",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Clearing outgoing items removes temporary Drop entries and file copies.",
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "drop.clear_outgoing",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.clear_incoming",
    title: "Clear Drop Incoming List",
    moduleId: "drop",
    module: "drop",
    description: "Clear DexNest Drop incoming metadata while keeping received files on disk.",
    category: "drop",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Clearing incoming removes Drop metadata from the desktop list.",
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "drop.clear_incoming",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.open_incoming_folder",
    title: "Open Drop Incoming Folder",
    moduleId: "drop",
    module: "drop",
    description: "Open the DexNest Drop incoming folder.",
    category: "drop",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "drop.open_incoming_folder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.open_outgoing_folder",
    title: "Open Drop Outgoing Folder",
    moduleId: "drop",
    module: "drop",
    description: "Open the DexNest Drop outgoing folder.",
    category: "drop",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "drop.open_outgoing_folder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "drop.clear_temp_shelf",
    title: "Clear Drop Temp Shelf",
    moduleId: "drop",
    module: "drop",
    description: "Clear temporary local Drop shelf items.",
    category: "drop",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Clearing the shelf removes temporary Drop entries.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "drop.clear_temp_shelf",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.open",
    title: "Open Tools",
    moduleId: "tools",
    module: "tools",
    description: "Open the DexNest Tools local utility workspace.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.tools",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.merge_pdfs",
    title: "Merge PDFs",
    moduleId: "tools",
    module: "tools",
    description: "Merge selected PDF files into a new local output PDF.",
    category: "tools.pdf",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.merge_pdfs",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.split_pdf",
    title: "Split PDF",
    moduleId: "tools",
    module: "tools",
    description: "Create a new PDF from a selected page range.",
    category: "tools.pdf",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.split_pdf",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.images_to_pdf",
    title: "Images to PDF",
    moduleId: "tools",
    module: "tools",
    description: "Create a PDF from selected local images.",
    category: "tools.pdf",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.images_to_pdf",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.compress_image",
    title: "Compress Image",
    moduleId: "tools",
    module: "tools",
    description: "Save compressed copies of selected images.",
    category: "tools.image",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.compress_image",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.resize_image",
    title: "Resize Image",
    moduleId: "tools",
    module: "tools",
    description: "Save resized copies of selected images.",
    category: "tools.image",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.resize_image",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.convert_image",
    title: "Convert Image",
    moduleId: "tools",
    module: "tools",
    description: "Convert selected images between local PNG and JPG outputs.",
    category: "tools.image",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.convert_image",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.open_output_folder",
    title: "Open Tools Output Folder",
    moduleId: "tools",
    module: "tools",
    description: "Open the DexNest Tools output folder.",
    category: "tools",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.open_output_folder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.send_output_to_drop",
    title: "Send Tools Output to Drop",
    moduleId: "tools",
    module: "tools",
    description: "Add a selected Tools output file to the DexNest Drop outgoing shelf.",
    category: "tools.drop",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.send_output_to_drop",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.mp4_to_mp3",
    title: "MP4 to MP3",
    moduleId: "tools",
    module: "tools",
    description: "Extract MP3 audio from selected local MP4 files with ffmpeg.",
    category: "tools.media",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.mp4_to_mp3",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.extract_audio",
    title: "Extract Audio",
    moduleId: "tools",
    module: "tools",
    description: "Extract audio from selected local video files with ffmpeg.",
    category: "tools.media",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.extract_audio",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.convert_audio",
    title: "Convert Audio",
    moduleId: "tools",
    module: "tools",
    description: "Convert selected local audio files to MP3, WAV, or M4A with ffmpeg.",
    category: "tools.media",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.convert_audio",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.docx_to_pdf",
    title: "DOCX to PDF",
    moduleId: "tools",
    module: "tools",
    description: "Convert selected DOCX files to local PDF outputs with LibreOffice.",
    category: "tools.office",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.docx_to_pdf",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.pptx_to_pdf",
    title: "PPTX to PDF",
    moduleId: "tools",
    module: "tools",
    description: "Convert selected PPTX files to local PDF outputs with LibreOffice.",
    category: "tools.office",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.pptx_to_pdf",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.pptx_to_images",
    title: "PPTX to Images",
    moduleId: "tools",
    module: "tools",
    description: "Export selected PPTX slides to local PNG images through LibreOffice and Poppler.",
    category: "tools.office",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.pptx_to_images",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.pdf_to_images",
    title: "PDF to Images",
    moduleId: "tools",
    module: "tools",
    description: "Export selected PDF pages to local PNG images with Poppler.",
    category: "tools.pdf",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.pdf_to_images",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.pdf_to_text",
    title: "PDF to Text",
    moduleId: "tools",
    module: "tools",
    description: "Export selected PDF text to local TXT files with Poppler.",
    category: "tools.pdf",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.pdf_to_text",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.pdf_to_docx_experimental",
    title: "PDF to DOCX Experimental",
    moduleId: "tools",
    module: "tools",
    description: "Attempt local PDF to DOCX conversion with LibreOffice. Quality may vary.",
    category: "tools.pdf",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.pdf_to_docx_experimental",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.ocr_image",
    title: "OCR Image",
    moduleId: "tools",
    module: "tools",
    description: "Run local Tesseract OCR on selected image files and save TXT outputs.",
    category: "tools.ocr",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.ocr_image",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.ocr_pdf",
    title: "OCR PDF",
    moduleId: "tools",
    module: "tools",
    description: "Run local Tesseract OCR on selected PDFs through local page images and save TXT outputs.",
    category: "tools.ocr",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.ocr_pdf",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.clean_scan",
    title: "Clean Scan",
    moduleId: "tools",
    module: "tools",
    description: "Apply local grayscale, contrast, sharpen, and rotation cleanup to scan images.",
    category: "tools.ocr",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.clean_scan",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.cleaned_image_to_pdf",
    title: "Cleaned Images to PDF",
    moduleId: "tools",
    module: "tools",
    description: "Clean selected scan images and create a local PDF output.",
    category: "tools.ocr",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.cleaned_image_to_pdf",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.open_ocr_settings",
    title: "Open OCR Settings",
    moduleId: "tools",
    module: "tools",
    description: "Open DexNest Tools OCR settings for Tesseract path and language.",
    category: "tools.settings",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.tools.settings",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.open_tools_settings",
    title: "Open Tools Settings",
    moduleId: "tools",
    module: "tools",
    description: "Open DexNest Tools dependency and output settings.",
    category: "tools.settings",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.tools.settings",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "tools.save_output_to_vault",
    title: "Save Tools Output to Vault",
    moduleId: "tools",
    module: "tools",
    description: "Copy a selected Tools output into DexNest Vault documents.",
    category: "tools.vault",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "tools.save_output_to_vault",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.open",
    title: "Open Vault",
    moduleId: "vault",
    module: "vault",
    description: "Open the DexNest Vault document library.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.vault",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.import_documents",
    title: "Import Vault Documents",
    moduleId: "vault",
    module: "vault",
    description: "Copy selected files into the local DexNest Vault document store.",
    category: "vault.documents",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "vault.import_documents",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.edit_document_metadata",
    title: "Edit Vault Document Metadata",
    moduleId: "vault",
    module: "vault",
    description: "Edit metadata for a stored DexNest Vault document.",
    category: "vault.documents",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.edit_document_metadata",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.delete_document",
    title: "Delete Vault Document",
    moduleId: "vault",
    module: "vault",
    description: "Delete a document record from DexNest Vault, optionally deleting the copied Vault file.",
    category: "vault.documents",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting from Vault can remove the copied Vault file. Originals outside Vault are never deleted.",
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "vault.delete_document",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.open_document",
    title: "Open Vault Document",
    moduleId: "vault",
    module: "vault",
    description: "Open a stored DexNest Vault document.",
    category: "vault.documents",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "vault.open_document",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.open_document_folder",
    title: "Open Vault Document Folder",
    moduleId: "vault",
    module: "vault",
    description: "Open the local folder containing a stored Vault document.",
    category: "vault.documents",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "vault.open_document_folder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.send_document_to_drop",
    title: "Send Vault Document to Drop",
    moduleId: "vault",
    module: "vault",
    description: "Add a stored Vault document to the DexNest Drop outgoing shelf.",
    category: "vault.drop",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "vault.send_document_to_drop",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.add_document_version",
    title: "Add Vault Document Version",
    moduleId: "vault",
    module: "vault",
    description: "Copy a new file as the next version of an existing Vault document.",
    category: "vault.versions",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "vault.add_document_version",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.show_expiring_soon",
    title: "Show Expiring Vault Documents",
    moduleId: "vault",
    module: "vault",
    description: "Show Vault documents expiring soon using local metadata only.",
    category: "vault.documents",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.show_expiring_soon",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  ...[
    ["vault.ocr.run_queue", "Run Vault OCR Queue", "Run queued Vault document OCR jobs using PaddleOCR GPU.", "vault.ocr", "caution", false],
    ["vault.ocr.pause_queue", "Pause Vault OCR Queue", "Pause the Vault OCR queue after the current job.", "vault.ocr", "safe", false],
    ["vault.ocr.retry_failed", "Retry Failed Vault OCR", "Queue failed Vault OCR jobs again.", "vault.ocr", "caution", false],
    ["vault.ocr.rerun_document", "Re-run Vault Document OCR", "Queue a selected Vault document for fresh PaddleOCR GPU OCR.", "vault.ocr", "caution", false],
    ["vault.ocr.open_text", "Open Vault OCR Text", "Open a Vault document OCR text sidecar.", "vault.ocr", "safe", false],
    ["vault.ocr.copy_text", "Copy Vault OCR Text", "Copy a Vault document OCR text sidecar to the clipboard.", "vault.ocr", "caution", false],
    ["vault.ocr.update_settings", "Update Vault OCR Settings", "Update DexNest Vault OCR queue settings.", "vault.ocr", "caution", false]
  ].map(([id, title, description, category, dangerLevel, requiresConfirmation]) => ({
    id: String(id),
    title: String(title),
    moduleId: "vault",
    module: "vault",
    description: String(description),
    category: String(category),
    dangerLevel: dangerLevel as "safe" | "caution" | "danger" | "critical",
    requiresConfirmation: Boolean(requiresConfirmation),
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function" as const,
    handlerRef: String(id),
    allowedTriggers: ["command", "deck", "module_ui"] as Array<"command" | "deck" | "voice" | "routine" | "module_ui">,
    enabled: true,
    status: "available" as const
  })),
  {
    id: "vault.secure.setup",
    title: "Set Up Secure Vault",
    moduleId: "vault",
    module: "vault",
    description: "Create the local encrypted DexNest Secure Vault.",
    category: "vault.secure",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.setup",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.unlock",
    title: "Unlock Secure Vault",
    moduleId: "vault",
    module: "vault",
    description: "Unlock DexNest Secure Vault with the master password.",
    category: "vault.secure",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.unlock",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.lock",
    title: "Lock Secure Vault",
    moduleId: "vault",
    module: "vault",
    description: "Forget the in-memory Secure Vault key.",
    category: "vault.secure",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.lock",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.create_item",
    title: "Create Secure Vault Item",
    moduleId: "vault",
    module: "vault",
    description: "Create an encrypted password, token, API key, or private note item.",
    category: "vault.secure",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.create_item",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.edit_item",
    title: "Edit Secure Vault Item",
    moduleId: "vault",
    module: "vault",
    description: "Edit encrypted Secure Vault item fields.",
    category: "vault.secure",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.edit_item",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.delete_item",
    title: "Delete Secure Vault Item",
    moduleId: "vault",
    module: "vault",
    description: "Delete an encrypted Secure Vault item.",
    category: "vault.secure",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a Secure Vault item cannot be undone.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.delete_item",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.copy_secret",
    title: "Copy Secure Vault Secret",
    moduleId: "vault",
    module: "vault",
    description: "Copy an encrypted Secure Vault secret to the clipboard.",
    category: "vault.secure",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.copy_secret",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.copy_username",
    title: "Copy Secure Vault Username",
    moduleId: "vault",
    module: "vault",
    description: "Copy a Secure Vault username to the clipboard.",
    category: "vault.secure",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.copy_username",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.export_encrypted",
    title: "Export Encrypted Secure Vault",
    moduleId: "vault",
    module: "vault",
    description: "Open the encrypted Secure Vault JSON file location for local backup.",
    category: "vault.secure",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "vault.secure.export_encrypted",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "vault.secure.import_encrypted_placeholder",
    title: "Import Encrypted Secure Vault Placeholder",
    moduleId: "vault",
    module: "vault",
    description: "Placeholder for future encrypted Secure Vault import.",
    category: "vault.secure",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "vault.secure.import_encrypted_placeholder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "placeholder"
  },
  {
    id: "search.open",
    title: "Open Search",
    moduleId: "search",
    module: "search",
    description: "Open the DexNest Search local file and metadata search workspace.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.search",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.rebuild_index",
    title: "Rebuild DexNest Search Index",
    moduleId: "search",
    module: "search",
    description: "Manually rebuild the local DexNest Search index from local-data metadata.",
    category: "search.index",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.rebuild_index",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.clear_index",
    title: "Clear DexNest Search Index",
    moduleId: "search",
    module: "search",
    description: "Clear the local DexNest Search index JSON file.",
    category: "search.index",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Clearing the Search index removes local index records until the next manual rebuild.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.clear_index",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.run_query",
    title: "Run Search Query",
    moduleId: "search",
    module: "search",
    description: "Run a local DexNest Search query against the manual index.",
    category: "search.query",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.run_query",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.secure.run",
    title: "Run Secure Vault Search",
    moduleId: "search",
    module: "search",
    description: "Run an in-memory Secure Vault admin search after master password confirmation.",
    category: "search.secure",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.secure.run",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.smart_lookup",
    title: "Run Smart Lookup",
    moduleId: "search",
    module: "search",
    description: "Answer a local rule-based question from indexed DexNest OCR and document text.",
    category: "search.smart_lookup",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.smart_lookup",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.smart_lookup_reveal",
    title: "Reveal Smart Lookup Answer",
    moduleId: "search",
    module: "search",
    description: "Reveal a masked Smart Lookup answer after confirmation.",
    category: "search.smart_lookup",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.smart_lookup_reveal",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.smart_lookup_copy_answer",
    title: "Copy Smart Lookup Answer",
    moduleId: "search",
    module: "search",
    description: "Copy a Smart Lookup answer to the clipboard with auto-clear.",
    category: "search.smart_lookup",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.smart_lookup_copy_answer",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.smart_lookup_open_source",
    title: "Open Smart Lookup Source",
    moduleId: "search",
    module: "search",
    description: "Open the local source document for a Smart Lookup result.",
    category: "search.smart_lookup",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.smart_lookup_open_source",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.save_query",
    title: "Save Search Query",
    moduleId: "search",
    module: "search",
    description: "Save the current DexNest Search query and filters locally.",
    category: "search.saved",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.save_query",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.delete_saved_query",
    title: "Delete Saved Search",
    moduleId: "search",
    module: "search",
    description: "Delete a saved DexNest Search query.",
    category: "search.saved",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a saved search removes it from local settings.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "search.delete_saved_query",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.open_result",
    title: "Open Search Result",
    moduleId: "search",
    module: "search",
    description: "Open the file behind a DexNest Search result when one exists.",
    category: "search.result",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "search.open_result",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.open_result_folder",
    title: "Open Search Result Folder",
    moduleId: "search",
    module: "search",
    description: "Open the folder behind a DexNest Search result or the local Search index folder.",
    category: "search.result",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "search.open_result_folder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "search.send_result_to_drop",
    title: "Send Search Result to Drop",
    moduleId: "search",
    module: "search",
    description: "Add a file Search result to the DexNest Drop outgoing shelf.",
    category: "search.drop",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "search.send_result_to_drop",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "journal.open",
    title: "Open Journal",
    moduleId: "journal",
    module: "journal",
    description: "Open the DexNest Journal private daily writing workspace.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.journal",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "journal.create_entry",
    title: "Create Journal Entry",
    moduleId: "journal",
    module: "journal",
    description: "Create a local DexNest Journal entry.",
    category: "journal.entries",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "journal.create_entry",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "journal.update_entry",
    title: "Update Journal Entry",
    moduleId: "journal",
    module: "journal",
    description: "Update local DexNest Journal entry metadata and text.",
    category: "journal.entries",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "journal.update_entry",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "journal.delete_entry",
    title: "Delete Journal Entry",
    moduleId: "journal",
    module: "journal",
    description: "Delete a local DexNest Journal entry.",
    category: "journal.entries",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a Journal entry removes its local JSON record.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "journal.delete_entry",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "journal.extract_events",
    title: "Extract Journal Events",
    moduleId: "journal",
    module: "journal",
    description: "Extract simple local Calendar candidates from a Journal entry.",
    category: "journal.calendar",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "journal.extract_events",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "journal.open_today",
    title: "Open Today's Journal",
    moduleId: "journal",
    module: "journal",
    description: "Open today's DexNest Journal entry view.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.journal",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.open",
    title: "Open Calendar",
    moduleId: "calendar",
    module: "calendar",
    description: "Open the DexNest local Calendar workspace.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.calendar",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.create_event",
    title: "Create Calendar Event",
    moduleId: "calendar",
    module: "calendar",
    description: "Create a local DexNest Calendar event.",
    category: "calendar.events",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.create_event",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.update_event",
    title: "Update Calendar Event",
    moduleId: "calendar",
    module: "calendar",
    description: "Update a local DexNest Calendar event.",
    category: "calendar.events",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.update_event",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.delete_event",
    title: "Delete Calendar Event",
    moduleId: "calendar",
    module: "calendar",
    description: "Delete a local DexNest Calendar event.",
    category: "calendar.events",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a Calendar event removes its local JSON record.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.delete_event",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.show_today",
    title: "Show Today's Calendar",
    moduleId: "calendar",
    module: "calendar",
    description: "Show today's local DexNest Calendar events.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.calendar",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.show_upcoming",
    title: "Show Upcoming Calendar",
    moduleId: "calendar",
    module: "calendar",
    description: "Show upcoming local DexNest Calendar events.",
    category: "calendar.events",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.show_upcoming",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.nudge.refresh",
    title: "Refresh Calendar Nudges",
    moduleId: "calendar",
    module: "calendar",
    description: "Regenerate local DexNest Calendar nudges from local sources.",
    category: "calendar.nudges",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.nudge.refresh",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.nudge.dismiss",
    title: "Dismiss Calendar Nudge",
    moduleId: "calendar",
    module: "calendar",
    description: "Dismiss a local DexNest Calendar nudge.",
    category: "calendar.nudges",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.nudge.dismiss",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.nudge.snooze",
    title: "Snooze Calendar Nudge",
    moduleId: "calendar",
    module: "calendar",
    description: "Snooze a local DexNest Calendar nudge.",
    category: "calendar.nudges",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.nudge.snooze",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.nudge.complete",
    title: "Complete Calendar Nudge",
    moduleId: "calendar",
    module: "calendar",
    description: "Mark a local DexNest Calendar nudge done.",
    category: "calendar.nudges",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.nudge.complete",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.nudge.open_source",
    title: "Open Calendar Nudge Source",
    moduleId: "calendar",
    module: "calendar",
    description: "Open the DexNest module that created a nudge.",
    category: "calendar.nudges",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.nudge.open_source",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "calendar.nudge.update_settings",
    title: "Update Calendar Nudge Settings",
    moduleId: "calendar",
    module: "calendar",
    description: "Update local DexNest Calendar nudge settings.",
    category: "calendar.nudges",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "calendar.nudge.update_settings",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  ...[
    ["heatmap.open", "Open Heatmap", "Open the DexNest Heatmap local usage view.", "navigation", "safe", false, "desktop.view.heatmap"],
    ["heatmap.start", "Start Heatmap Tracking", "Start lightweight local Heatmap sampling.", "heatmap.tracking", "caution", false, "heatmap.start"],
    ["heatmap.pause", "Pause Heatmap Tracking", "Pause local Heatmap sampling.", "heatmap.tracking", "safe", false, "heatmap.pause"],
    ["heatmap.log_current_app", "Log Current App", "Log the current active app/window once.", "heatmap.sample", "caution", false, "heatmap.log_current_app"],
    ["heatmap.aggregate_now", "Aggregate Heatmap Now", "Aggregate local Heatmap samples now.", "heatmap.aggregate", "safe", false, "heatmap.aggregate_now"],
    ["heatmap.create_goal", "Create Heatmap Goal", "Create a local Heatmap weekly goal.", "heatmap.goals", "caution", false, "heatmap.create_goal"],
    ["heatmap.update_goal", "Update Heatmap Goal", "Update a local Heatmap goal.", "heatmap.goals", "caution", false, "heatmap.update_goal"],
    ["heatmap.delete_goal", "Delete Heatmap Goal", "Delete a local Heatmap goal.", "heatmap.goals", "danger", true, "heatmap.delete_goal"],
    ["heatmap.clear_data", "Clear Heatmap Data", "Clear local Heatmap samples.", "heatmap.data", "danger", true, "heatmap.clear_data"]
  ].map(([id, title, description, category, dangerLevel, requiresConfirmation, handlerRef]) => ({
    id: id as string,
    title: title as string,
    moduleId: "heatmap" as const,
    module: "heatmap" as const,
    description: description as string,
    category: category as string,
    dangerLevel: dangerLevel as "safe" | "caution" | "danger" | "critical",
    requiresConfirmation: requiresConfirmation as boolean,
    confirmationRule: requiresConfirmation ? "Heatmap data changes need confirmation." : null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function" as const,
    handlerRef: handlerRef as string,
    allowedTriggers: ["command", "deck", "routine", "module_ui"] as Array<"command" | "deck" | "routine" | "module_ui">,
    enabled: true,
    status: "available" as const
  })),
  {
    id: "voice.start_dictation_placeholder",
    title: "Start Voice Dictation",
    moduleId: "voice",
    module: "voice",
    description: "Start click-to-speak dictation when browser SpeechRecognition is available, otherwise show a local fallback.",
    category: "voice.input",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "voice.start_dictation_placeholder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "placeholder"
  },
  {
    id: "finder.open",
    title: "Open Finder",
    moduleId: "finder",
    module: "finder",
    description: "Open the DexNest Finder item-location memory workspace.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.finder",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.create_item",
    title: "Create Finder Item",
    moduleId: "finder",
    module: "finder",
    description: "Create a local DexNest Finder item-location record.",
    category: "finder.items",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.create_item",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.update_item",
    title: "Update Finder Item",
    moduleId: "finder",
    module: "finder",
    description: "Update a local DexNest Finder item-location record.",
    category: "finder.items",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.update_item",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.delete_item",
    title: "Delete Finder Item",
    moduleId: "finder",
    module: "finder",
    description: "Delete a local DexNest Finder item-location record.",
    category: "finder.items",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a Finder item removes its local JSON record.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.delete_item",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.archive_item",
    title: "Archive Finder Item",
    moduleId: "finder",
    module: "finder",
    description: "Archive a DexNest Finder item without deleting it.",
    category: "finder.items",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.archive_item",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.mark_moved",
    title: "Mark Finder Item Moved",
    moduleId: "finder",
    module: "finder",
    description: "Update where a DexNest Finder item is stored.",
    category: "finder.location",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.mark_moved",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.mark_lent_out",
    title: "Mark Finder Item Lent Out",
    moduleId: "finder",
    module: "finder",
    description: "Mark a DexNest Finder item as lent out.",
    category: "finder.location",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.mark_lent_out",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.mark_returned",
    title: "Mark Finder Item Returned",
    moduleId: "finder",
    module: "finder",
    description: "Mark a lent DexNest Finder item as returned home.",
    category: "finder.location",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.mark_returned",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.search_items",
    title: "Search Finder Items",
    moduleId: "finder",
    module: "finder",
    description: "Search local DexNest Finder item-location metadata.",
    category: "finder.search",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.search_items",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finder.reverse_lookup",
    title: "Reverse Lookup Finder Location",
    moduleId: "finder",
    module: "finder",
    description: "Find what DexNest Finder items are stored in a location or container.",
    category: "finder.search",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finder.reverse_lookup",
    allowedTriggers: ["command", "deck", "voice", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "capture.open",
    title: "Open Capture",
    moduleId: "capture",
    module: "capture",
    description: "Open the DexNest Capture shared inbox.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.capture",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  ...[
    ["capture.create_note", "Create Capture Note", "Create a local DexNest Capture inbox item.", "capture.inbox", "caution", false],
    ["capture.create_from_clipboard", "Create Capture from Clipboard", "Create a DexNest Capture item from the current clipboard text.", "capture.inbox", "caution", false],
    ["capture.create_from_file", "Create Capture from File", "Copy a local file into DexNest Capture.", "capture.inbox", "caution", false],
    ["capture.route_to_journal", "Route Capture to Journal", "Create a local Journal entry from a Capture item.", "capture.routing", "caution", false],
    ["capture.route_to_calendar", "Route Capture to Calendar", "Create a local Calendar event from a Capture item.", "capture.routing", "caution", false],
    ["capture.route_to_vault", "Route Capture to Vault", "Save an attached Capture file into DexNest Vault.", "capture.routing", "caution", false],
    ["capture.route_to_finance", "Route Capture to Finance", "Create a local Finance expense from a Capture item.", "capture.routing", "caution", false],
    ["capture.route_to_finder", "Route Capture to Finder", "Create a local Finder item from a Capture item.", "capture.routing", "caution", false],
    ["capture.route_to_drop", "Route Capture to Drop", "Send Capture text or file to DexNest Drop.", "capture.routing", "caution", false],
    ["capture.archive_item", "Archive Capture Item", "Archive a DexNest Capture item.", "capture.inbox", "caution", false],
    ["capture.delete_item", "Delete Capture Item", "Delete a DexNest Capture item.", "capture.inbox", "danger", true]
  ].map(([id, title, description, category, dangerLevel, requiresConfirmation]) => ({
    id: id as string,
    title: title as string,
    moduleId: "capture" as const,
    module: "capture" as const,
    description: description as string,
    category: category as string,
    dangerLevel: dangerLevel as "safe" | "caution" | "danger" | "critical",
    requiresConfirmation: requiresConfirmation as boolean,
    confirmationRule: requiresConfirmation ? "Deleting a Capture item removes it from the active shared inbox." : null,
    reversible: false,
    undoActionId: null,
    handlerType: id === "capture.create_from_file" || id === "capture.route_to_vault" || id === "capture.route_to_drop" ? "file_operation" as const : "internal_function" as const,
    handlerRef: id as string,
    allowedTriggers: ["command", "deck", "module_ui"] as Array<"command" | "deck" | "module_ui">,
    enabled: true,
    status: "available" as const
  })),
  {
    id: "finance.open",
    title: "Open Finance",
    moduleId: "finance",
    module: "finance",
    description: "Open the DexNest Finance local expense workspace.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.finance",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.create_transaction",
    title: "Create Finance Transaction",
    moduleId: "finance",
    module: "finance",
    description: "Create a local DexNest Finance transaction.",
    category: "finance.transactions",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.create_transaction",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.update_transaction",
    title: "Update Finance Transaction",
    moduleId: "finance",
    module: "finance",
    description: "Update a local DexNest Finance transaction.",
    category: "finance.transactions",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.update_transaction",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.delete_transaction",
    title: "Delete Finance Transaction",
    moduleId: "finance",
    module: "finance",
    description: "Delete local DexNest Finance transaction metadata.",
    category: "finance.transactions",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a transaction removes the local finance record.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.delete_transaction",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.attach_receipt",
    title: "Attach Finance Receipt",
    moduleId: "finance",
    module: "finance",
    description: "Copy a receipt file into DexNest local receipt storage.",
    category: "finance.receipts",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "finance.attach_receipt",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.send_receipt_to_drop",
    title: "Send Finance Receipt to Drop",
    moduleId: "finance",
    module: "finance",
    description: "Add a finance receipt file to DexNest Drop outgoing shelf.",
    category: "finance.receipts",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "finance.send_receipt_to_drop",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.save_receipt_to_vault",
    title: "Save Finance Receipt to Vault",
    moduleId: "finance",
    module: "finance",
    description: "Save a finance receipt file into DexNest Vault.",
    category: "finance.receipts",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "file_operation",
    handlerRef: "finance.save_receipt_to_vault",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.create_recurring",
    title: "Create Recurring Expense",
    moduleId: "finance",
    module: "finance",
    description: "Create a local DexNest recurring expense.",
    category: "finance.recurring",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.create_recurring",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.update_recurring",
    title: "Update Recurring Expense",
    moduleId: "finance",
    module: "finance",
    description: "Update a local DexNest recurring expense.",
    category: "finance.recurring",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.update_recurring",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.delete_recurring",
    title: "Delete Recurring Expense",
    moduleId: "finance",
    module: "finance",
    description: "Delete a local DexNest recurring expense.",
    category: "finance.recurring",
    dangerLevel: "danger",
    requiresConfirmation: true,
    confirmationRule: "Deleting a recurring expense removes its local finance record.",
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.delete_recurring",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.toggle_recurring",
    title: "Toggle Recurring Expense",
    moduleId: "finance",
    module: "finance",
    description: "Mark a DexNest recurring expense active or inactive.",
    category: "finance.recurring",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.toggle_recurring",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.create_return_reminder",
    title: "Create Return Reminder",
    moduleId: "finance",
    module: "finance",
    description: "Create a local Calendar reminder for a finance return deadline.",
    category: "finance.calendar",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.create_return_reminder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.create_warranty_reminder",
    title: "Create Warranty Reminder",
    moduleId: "finance",
    module: "finance",
    description: "Create a local Calendar reminder for a finance warranty date.",
    category: "finance.calendar",
    dangerLevel: "caution",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.create_warranty_reminder",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "finance.show_monthly_summary",
    title: "Show Finance Monthly Summary",
    moduleId: "finance",
    module: "finance",
    description: "Show the local DexNest Finance monthly summary.",
    category: "finance.summary",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "finance.show_monthly_summary",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "audit.open_history",
    title: "Open Audit History",
    moduleId: "command",
    module: "command",
    description: "Open recent DexNest event history.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.audit",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  },
  {
    id: "settings.open",
    title: "Open Settings",
    moduleId: "command",
    module: "command",
    description: "Open DexNest local settings.",
    category: "navigation",
    dangerLevel: "safe",
    requiresConfirmation: false,
    confirmationRule: null,
    reversible: false,
    undoActionId: null,
    handlerType: "internal_function",
    handlerRef: "desktop.view.settings",
    allowedTriggers: ["command", "deck", "module_ui"],
    enabled: true,
    status: "available"
  }
] as DexNestActionDefinition[];

export function validateActionDefinition(action: DexNestActionDefinition): void {
  if (!actionIdPattern.test(action.id)) {
    throw new Error(`DexNest action id must be dot-delimited lowercase text: ${action.id}`);
  }

  if (!action.title.trim()) {
    throw new Error(`DexNest action ${action.id} must have a title.`);
  }

  if (!action.description.trim()) {
    throw new Error(`DexNest action ${action.id} must have a description.`);
  }

  if (!action.enabled) {
    throw new Error(`DexNest action ${action.id} must be enabled or omitted from the registry.`);
  }
}

export function createActionRegistry(initialActions: DexNestActionDefinition[] = []) {
  const actions = new Map<string, DexNestActionDefinition>();

  function register(action: DexNestActionDefinition): void {
    validateActionDefinition(action);

    if (actions.has(action.id)) {
      throw new Error(`DexNest action already registered: ${action.id}`);
    }

    actions.set(action.id, action);
  }

  for (const action of initialActions) {
    register(action);
  }

  return {
    register,
    get(actionId: string) {
      return actions.get(actionId);
    },
    list() {
      return [...actions.values()];
    }
  };
}
